import type { FaqItem } from "@/lib/tutor/types";
import intro from "./intro.json";
import parts_of_speech from "./parts-of-speech.json";
import adjectives_adverbs from "./adjectives-adverbs.json";
import agreement_narration from "./agreement-narration.json";
import articles from "./articles.json";
import comparison from "./comparison.json";
import conjunctions from "./conjunctions.json";
import gerunds from "./gerunds.json";
import modals from "./modals.json";
import nouns from "./nouns.json";
import participial_constructions from "./participial-constructions.json";
import participles from "./participles.json";
import passive from "./passive.json";
import phrase_clause from "./phrase-clause.json";
import prepositions from "./prepositions.json";
import pronouns from "./pronouns.json";
import relatives from "./relatives.json";
import sentence_elements from "./sentence-elements.json";
import sentence_patterns from "./sentence-patterns.json";
import sentence_types from "./sentence-types.json";
import special_constructions from "./special-constructions.json";
import subjunctive from "./subjunctive.json";
import suneung from "./suneung.json";
import tenses from "./tenses.json";
import to_infinitive from "./to-infinitive.json";
import verbals_review from "./verbals-review.json";
import verbs_basics from "./verbs-basics.json";

/** 질문 도우미의 질문 은행. scripts/merge-drafts.py가 공개된 장의 content/faq/*.json을 모아 만든다. */
export const faq: FaqItem[] = [...intro, ...parts_of_speech, ...adjectives_adverbs, ...agreement_narration, ...articles, ...comparison, ...conjunctions, ...gerunds, ...modals, ...nouns, ...participial_constructions, ...participles, ...passive, ...phrase_clause, ...prepositions, ...pronouns, ...relatives, ...sentence_elements, ...sentence_patterns, ...sentence_types, ...special_constructions, ...subjunctive, ...suneung, ...tenses, ...to_infinitive, ...verbals_review, ...verbs_basics] as FaqItem[];
